lib/phoenix_elixir_hongcheng_web/router.ex
defmodule PhoenixElixirHongchengWeb.Router do
  use PhoenixElixirHongchengWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PhoenixElixirHongchengWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/elevio", ElevioController, :index
    get "/elevio/details", ElevioController, :details
  end

  # Other scopes may use custom stacks.
  # scope "/api", PhoenixElixirHongchengWeb do
  #   pipe_through :api
  # end
end

lib/phoenix_elixir_hongcheng/application.ex
defmodule PhoenixElixirHongcheng.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the endpoint when the application starts
      PhoenixElixirHongchengWeb.Endpoint
      # Starts a worker by calling: PhoenixElixirHongcheng.Worker.start_link(arg)
      # {PhoenixElixirHongcheng.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: PhoenixElixirHongcheng.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    PhoenixElixirHongchengWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/phoenix_elixir_hongcheng_web/controllers/elevio_controller.ex
defmodule PhoenixElixirHongchengWeb.ElevioController do
  require Logger

  use PhoenixElixirHongchengWeb, :controller

  def index(conn, params) do
    search_term = get_in(params, ["query"])
    page = get_in(params, ["page"])
    Logger.debug "search param : #{search_term}"
    Logger.debug "page : #{page}"

    if search_term == nil || String.length(search_term) === 0 do
      # Initial first page of all article
      {status, result} = ElevioClient.get_all_articles(page)
      if status == :ok do
        total_pages = result["total_pages"]

        # Create an array of pages
        pages = Enum.reduce 1..total_pages, [] , fn page, list ->
          list ++ [page]
        end

        render(conn, "index.html", articles: result["articles"], search: "", pages: pages)
      else
        render(conn, "index.html", articles: [], search: "", pages: [])
      end
    else
      # Search article result
      {status, result} = ElevioClient.search_article("en", page, search_term)
      if status == :ok do
        total_pages = result["totalPages"]

        if total_pages > 0 do
          pages = Enum.reduce 1..total_pages, [] , fn page, list ->
            list ++ [page]
          end
          render(conn, "index.html", articles: result["results"], search: search_term, pages: pages)
        else
          render(conn, "index.html", articles: result["results"], search: search_term, pages: [])
        end
      else
        render(conn, "index.html", articles: [], pages: [])
      end
    end
  end

  def details(conn, params) do
    id = get_in(params, ["id"])
    {status, result} = ElevioClient.get_article(String.to_integer(id))
    if status == :ok do
      Logger.debug "result #{inspect result}"
      if length(result["article"]["translations"]) > 0 do
        render(conn, "details.html", body: Enum.at(result["article"]["translations"],0)["body"])
      else
        render(conn, "details.html", body: "N/A")
      end
    else
      render(conn, "details.html", body: "N/A")
    end
  end
end

lib/phoenix_elixir_hongcheng_web/controllers/page_controller.ex
defmodule PhoenixElixirHongchengWeb.PageController do
  use PhoenixElixirHongchengWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/phoenix_elixir_hongcheng_web/views/elevio_view.ex
defmodule PhoenixElixirHongchengWeb.ElevioView do
  use PhoenixElixirHongchengWeb, :view
end

lib/phoenix_elixir_hongcheng_web/views/error_view.ex
defmodule PhoenixElixirHongchengWeb.ErrorView do
  use PhoenixElixirHongchengWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/phoenix_elixir_hongcheng_web/views/layout_view.ex
defmodule PhoenixElixirHongchengWeb.LayoutView do
  use PhoenixElixirHongchengWeb, :view
end

lib/phoenix_elixir_hongcheng_web/views/page_view.ex
defmodule PhoenixElixirHongchengWeb.PageView do
  use PhoenixElixirHongchengWeb, :view
end

lib/phoenix_elixir_hongcheng_web/templates/elevio/details.html.eex
<h2>Article Details</h2>
<p>
<%= raw(@body)%>
</p>
<a href="<%= Routes.elevio_path(@conn, :index) %>" class="btn btn-info" role="button">Back</a>

lib/phoenix_elixir_hongcheng_web/templates/elevio/index.html.eex
<div class="container">
  <h2>Listing articles</h2>
  <nav class="navbar">
    <div class="container-fluid">
      <%= form_for @conn, Routes.elevio_path(@conn, :index), [method: :get, class: "navbar-form navbar-right"], fn f -> %>
          <div class="form-group">
              <%= search_input f, :query %>
          </div>
          <%= submit "Search", class: "btn btn-default" %>
      <% end %>
    </div>
  </nav>
  <div>
    <%= for article <- @articles do %>
        => <a href="<%= Routes.elevio_path(@conn, :details) %>?id=<%= article["id"] %> "> <%= article["title"] %> </a></br>
    <% end %>
  </div>
  <ul class="pagination">
    <%= for page <- @pages do %>
      <li><a href="<%= Routes.elevio_path(@conn, :index) %>?page=<%= page %>&query=<%= @search%>"><%= page %></a></li>
    <% end %>
  </ul>
</div>

lib/phoenix_elixir_hongcheng_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>PhoenixElixirHongcheng · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ul>
            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li>
          </ul>
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/phoenix_elixir_hongcheng_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed or maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>